export const REMOVE_REPOSITORIES = 'REMOVE_REPOSITORIES';
export const ADD_REPOSITORY = 'ADD_REPOSITORY';
export const SELECT_REPOSITORIES = 'SELECT_REPOSITORIES';
export const UPDATE_REPOSITORIES = 'UPDATE_REPOSITORIES';

export const GET_STATUSES_DONE = 'GET_STATUSES_DONE';
export const GET_STATUSES_FAILED = 'GET_STATUSES_FAILED';

export const GET_STATISTICS = 'GET_STATISTICS';
export const GET_STATISTICS_DONE = 'GET_STATISTICS_DONE';
export const GET_STATISTICS_FAILED = 'GET_STATISTICS_FAILED';

export const REMOVE_USERS = 'REMOVE_USERS';
export const ADD_USER = 'ADD_USER';
export const SELECT_USER = 'SELECT_USER';