import { resolve } from 'path'

export const REPOS_PATH = resolve(__dirname, "../../../Skylight") // path to folder with all repos
export const REPOS = [
    'dibels8-classroom-reports',
    'mbark',
    'dibels8-classroom-reports-selenium',
    'selenium-skylight',
    'asiaq_skylight_config',
    'amplify-components',
    'styles-dev',
    'skylight',
    'pdf-generator-lambda',
    'asiaq_rocket_config',
    'terraform-skylight-config',
    'terraform-config',
    'service-clients',
    'scone',
    'core-assessment-lib-java',
    'd2-sql',
    'd2-hc-sql',
    'mclass-documentation',
    'lantern_pras',
    'asiaq_astro_config',
    'dibels8-apis',
    'trc-lib-java',
    'mclass-lambda-common',
    'asiaq_quality_config',
    'skylight-build',
    'idel2-apis',
    'skylight-instruction-ui',
    'model-gatherer',
    'math-lib-java',
    'joule-lib-java',
    'java-tables',
    'java-logging',
    'dibels-lib-java',
    'component-framework',
    'burst-lib-java',
    'beacon-build-submodule',
    'java-build-tools',
    'model-txdb-wgen',
    'wgspring',
    'webapp-build',
    'asiaq_arrested_config',
    'classroom-reports-activities'
];

export const GIT_USERS = [
   "rpaslavskyy",
   "smerlyuk",
   "akuzmichov",
   "tsemashov",
   "mtomashivska",
   "okyrychenko",
   "mtlumak",
   "akornilo",
   "achernivchan",
   "bkoroliuk",
   "mstoiko",
   "okrasnokutskyi",
   "vkrasov",
   "yshevchenko",
];

export const START_DATE = '07/01/2020';
export const DATE_FORMAT = 'MM/DD/YYYY';